### ISSUE TITLE
features/improvements checklist

### ISSUE THREAD

**Issue by mrparkerlol** [mrparkerlol/script-builder-backend#1]
- [ ]  Add support for reading Roblox's binary file format
- [ ]  Add support for reading Roblox's XML format
- [ ]  Switch from faunaDB to Cloudflare's Durable Objects and KV (once durable objects are GA)
- [ ]  Clean up repository and code
- [ ]  Add support for modifying modules and models for sandboxing
- [ ]  Add support for game:GetObjects() for script builder (relies on above)
- [ ]  Add support for saved scripts to be used anywhere, but allow that to be toggled by individual place owners
